import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { encodePng } from '../scripts/generate-app-icon.mjs';
import {
  inspectIco,
  parsePackageIconUrl,
  sha256,
  validateBrandMaster,
  verifyBrandReleaseIntegrity,
} from '../scripts/verify-brand-release-integrity.mjs';
import {
  validateNormalizedPackagedIconProof,
  verifyPackagedIconProof,
} from '../scripts/verify-packaged-icon-proof.mjs';

const root = resolve(import.meta.dirname, '..');
const temporaryRoots: string[] = [];

afterEach(() => {
  for (const directory of temporaryRoots.splice(0)) rmSync(directory, { recursive: true, force: true });
});

function makePe(marker: number): Buffer {
  const bytes = Buffer.alloc(256, marker);
  bytes[0] = 0x4d;
  bytes[1] = 0x5a;
  bytes.writeUInt32LE(64, 0x3c);
  Buffer.from([0x50, 0x45, 0, 0]).copy(bytes, 64);
  return bytes;
}

function packagedFixture() {
  const fixtureRoot = mkdtempSync(join(tmpdir(), 'material-cookie-clicker-icon-proof-'));
  temporaryRoots.push(fixtureRoot);
  const proofRoot = join(fixtureRoot, 'icon-proof');
  mkdirSync(proofRoot);
  const setupExecutablePath = join(fixtureRoot, 'MaterialCookieClicker-Setup.exe');
  const applicationExecutablePath = join(fixtureRoot, 'Material Cookie Clicker.exe');
  writeFileSync(setupExecutablePath, makePe(0x11));
  writeFileSync(applicationExecutablePath, makePe(0x22));

  const sourceIcon = readFileSync(resolve(root, 'assets/material-cookie-clicker.ico'));
  const inspection = inspectIco(sourceIcon);
  const iconProof: Array<Record<string, unknown>> = [];
  for (const [label, executable] of [['setup', setupExecutablePath], ['app', applicationExecutablePath]] as const) {
    for (const size of [16, 32] as const) {
      const pixels = inspection.pixelsBySize.get(size)!;
      const image = encodePng(size, size, pixels);
      const filename = `${label}-${size}.png`;
      writeFileSync(join(proofRoot, filename), image);
      iconProof.push({
        executable: basename(executable),
        label,
        size,
        path: filename,
        bytes: image.length,
        sha256: sha256(image),
      });
    }
  }
  const manifestPath = join(fixtureRoot, 'installer-manifest.json');
  const sourceCommit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
  const manifest = {
    schemaVersion: 'material-cookie-clicker.local-installer.v2',
    sourceCommit,
    iconProof,
  };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  return { fixtureRoot, proofRoot, setupExecutablePath, applicationExecutablePath, manifestPath, manifest, inspection };
}

describe('brand release integrity', () => {
  it('reproduces the current ICO and binds every package icon field to its immutable matching blob', async () => {
    const proof = await verifyBrandReleaseIntegrity({ root, networkMode: 'local' });
    expect(proof.schemaVersion).toBe('material-cookie-clicker.brand-release.v1');
    expect(proof.generator.iconSizes).toEqual([16, 32, 48, 256]);
    expect(proof.icon.frames.map((frame) => frame.size)).toEqual([16, 32, 48, 256]);
    expect(proof.icon.frames.every((frame) => frame.bitDepth === 32 && frame.alphaRange.join(',') === '0,255')).toBe(true);
    expect(proof.icon.gitBlobSha1).toBe('7a4af0c6cce0b8f49ec4bb992e40cb0940c12b03');
    expect(proof.packageIconUrl.commit).toBe('416d3805761d58a9b626f4d0207b004bef396731');
    expect(proof.packageIconUrl.commit).not.toBe('a98e38c07423a7cfb4cb3190412884a404a7245e');
    expect(proof.packageIconUrl.sha256).toBe(proof.icon.sha256);
    expect(proof.packageIconUrl.matchesCurrentIcon).toBe(true);
  });

  it('rejects the stale a98e URL, a changed generated byte, and a missing ICO frame before returning green', async () => {
    await expect(verifyBrandReleaseIntegrity({ root, networkMode: 'local', mutation: 'stale-url' })).rejects.toThrow(/fa1e7f8d.*7a4af0c6/s);
    await expect(verifyBrandReleaseIntegrity({ root, networkMode: 'local', mutation: 'generated-byte' })).rejects.toThrow(/not the exact output/);
    const icon = Buffer.from(readFileSync(resolve(root, 'assets/material-cookie-clicker.ico')));
    icon.writeUInt16LE(3, 4);
    expect(() => inspectIco(icon)).toThrow(/contains 3 frames; expected exactly 4/);
    await expect(verifyBrandReleaseIntegrity({ root, networkMode: 'local' })).resolves.toMatchObject({
      packageIconUrl: { matchesCurrentIcon: true },
    });
  });

  it('rejects mutable or embellished icon URLs and active content in the master', () => {
    expect(() => parsePackageIconUrl('https://raw.githubusercontent.com/Ding-Ding-Projects/material-cookie-clicker/main/assets/material-cookie-clicker.ico')).toThrow(/immutable full-commit/);
    expect(() => parsePackageIconUrl('https://raw.githubusercontent.com/Ding-Ding-Projects/material-cookie-clicker/416d3805761d58a9b626f4d0207b004bef396731/assets/material-cookie-clicker.ico?download=1')).toThrow(/query parameters/);
    const master = readFileSync(resolve(root, 'assets/material-cookie-clicker-logo-master.svg'), 'utf8');
    expect(() => validateBrandMaster(master.replace('</svg>', '<script>alert(1)</script></svg>'))).toThrow(/free of scripts/);
    expect(validateBrandMaster(master).canvas).toBe(512);
  });

  it('verifies the immutable HTTPS bytes when local Git history is intentionally bypassed', async () => {
    const icon = readFileSync(resolve(root, 'assets/material-cookie-clicker.ico'));
    const fetchImpl = async () => ({ ok: true, status: 200, arrayBuffer: async () => icon });
    const proof = await verifyBrandReleaseIntegrity({ root, networkMode: 'https', fetchImpl });
    expect(proof.packageIconUrl.verificationSource).toBe('https');
    expect(proof.packageIconUrl.sha256).toBe(sha256(icon));
    const staleFetch = async () => ({ ok: true, status: 200, arrayBuffer: async () => Buffer.from('stale') });
    await expect(verifyBrandReleaseIntegrity({ root, networkMode: 'https', fetchImpl: staleFetch })).rejects.toThrow(/immutable icon URL serves SHA-256/);
  });

  it('proves the deliberate CLI mutations red and the restored contract green', () => {
    for (const mutation of ['stale-url', 'generated-byte', 'missing-frame']) {
      const red = spawnSync(process.execPath, ['scripts/verify-brand-release-integrity.mjs', '--network', 'local', '--mutate', mutation], { cwd: root, encoding: 'utf8' });
      expect(red.status, `${mutation} unexpectedly passed`).toBe(1);
      expect(red.stderr).toContain('Brand release integrity failed:');
    }
    const green = spawnSync(process.execPath, ['scripts/verify-brand-release-integrity.mjs', '--network', 'local'], { cwd: root, encoding: 'utf8' });
    expect(green.status).toBe(0);
    expect(green.stdout).toContain('Brand release integrity verified:');
  });
});

describe('packaged Setup and application icon proof', () => {
  it('normalizes exact 16px and 32px extracted pixels for both PE artifacts', async () => {
    const fixture = packagedFixture();
    const proof = await verifyPackagedIconProof({
      root,
      manifestPath: fixture.manifestPath,
      proofRoot: fixture.proofRoot,
      setupExecutablePath: fixture.setupExecutablePath,
      applicationExecutablePath: fixture.applicationExecutablePath,
      verifiedAt: '2026-08-19T12:00:00.000Z',
      networkMode: 'local',
    });
    expect(proof.schemaVersion).toBe('material-cookie-clicker.packaged-icon-proof.v1');
    expect(proof.sourceIcon.frames.map((frame) => frame.size)).toEqual([16, 32, 48, 256]);
    expect(proof.artifacts.map((artifact) => artifact.kind)).toEqual(['setup', 'application']);
    expect(proof.artifacts.flatMap((artifact) => artifact.extractedIcons.map((icon) => `${artifact.kind}-${icon.size}-${icon.matchesSource}`))).toEqual([
      'setup-16-true', 'setup-32-true', 'application-16-true', 'application-32-true',
    ]);
    expect(validateNormalizedPackagedIconProof(proof)).toBe(proof);
  });

  it('turns red for missing records, stale digests, missing commit binding, and changed pixels, then green after restoration', async () => {
    const fixture = packagedFixture();
    const options = {
      root,
      manifestPath: fixture.manifestPath,
      proofRoot: fixture.proofRoot,
      setupExecutablePath: fixture.setupExecutablePath,
      applicationExecutablePath: fixture.applicationExecutablePath,
      verifiedAt: '2026-08-19T12:00:00.000Z',
      networkMode: 'local',
    };
    await expect(verifyPackagedIconProof({ ...options, mutation: 'missing-setup' })).rejects.toThrow(/exactly four/);
    await expect(verifyPackagedIconProof({ ...options, mutation: 'wrong-record-digest' })).rejects.toThrow(/digest differs/);
    await expect(verifyPackagedIconProof({ ...options, mutation: 'missing-source-commit' })).rejects.toThrow(/sourceCommit/);

    const record = fixture.manifest.iconProof.find((item) => item.label === 'setup' && item.size === 16)!;
    const wrongPixels = Buffer.from(fixture.inspection.pixelsBySize.get(16)!);
    wrongPixels[0] ^= 0xff;
    const wrongImage = encodePng(16, 16, wrongPixels);
    writeFileSync(join(fixture.proofRoot, record.path as string), wrongImage);
    record.bytes = wrongImage.length;
    record.sha256 = sha256(wrongImage);
    writeFileSync(fixture.manifestPath, `${JSON.stringify(fixture.manifest, null, 2)}\n`);
    await expect(verifyPackagedIconProof(options)).rejects.toThrow(/extracted pixels do not match/);

    const correctPixels = fixture.inspection.pixelsBySize.get(16)!;
    const correctImage = encodePng(16, 16, correctPixels);
    writeFileSync(join(fixture.proofRoot, record.path as string), correctImage);
    record.bytes = correctImage.length;
    record.sha256 = sha256(correctImage);
    writeFileSync(fixture.manifestPath, `${JSON.stringify(fixture.manifest, null, 2)}\n`);
    await expect(verifyPackagedIconProof(options)).resolves.toMatchObject({
      artifacts: [{ kind: 'setup' }, { kind: 'application' }],
    });
  });

  it('keeps the committed schema exact and fail-closed', () => {
    const schema = JSON.parse(readFileSync(resolve(root, 'scripts/packaged-icon-proof.schema.json'), 'utf8'));
    expect(schema.additionalProperties).toBe(false);
    expect(schema.required).toEqual(['schemaVersion', 'sourceCommit', 'sourceIcon', 'artifacts', 'verifiedAt']);
    expect(schema.properties.schemaVersion.const).toBe('material-cookie-clicker.packaged-icon-proof.v1');
    expect(schema.properties.sourceIcon.properties.frames.prefixItems).toHaveLength(4);
    expect(schema.properties.artifacts.prefixItems).toEqual([
      { $ref: '#/$defs/setupArtifact' },
      { $ref: '#/$defs/applicationArtifact' },
    ]);
  });
});
